main: com.cavetale.raid.RaidPlugin
name: Raid
version: 0.1
api-version: 1.13
description: Turn worlds into raids
author: StarTux
website: https://cavetale.com
depend: [WorldMarker]
softdepend: []
commands:

  raid:
    aliases: []
    description: Join the Raid
    permission: raid.raid
    usage: /raid - Join the raid

  raidedit:
    aliases: []
    description: Raid Editor Command
    permission: raid.raid
    permission-message: You do not have permission!
    usage: /raidedit

permissions:
  raid.raid:
    description: Use /raid
    default: op

  raid.edit:
    description: Use /raidedit
    default: op
