main: com.cavetale.raid.RaidPlugin
name: Raid
version: 0.1
api-version: 1.18
description: Turn worlds into raids
author: StarTux
website: https://cavetale.com
depend: [Core, WorldMarker, Mytems, Sidebar, Enemy, WorldEdit, PlayerCache, Fam, BlockClip, Editor]
softdepend: []
commands:

  raid:
    aliases: [back]
    description: Join the Raid
    permission: raid.raid
    usage: /raid - Join the raid

  raidedit:
    aliases: [redit]
    description: Raid Editor Command
    permission: raid.edit
    permission-message: You do not have permission!
    usage: /raidedit

permissions:
  raid.raid:
    description: Use /raid
    default: op

  raid.edit:
    description: Use /raidedit
    default: op
